version = "1.0"

[main]
name.en = "Cacti web configuration"
name.fr = "Configuration du site Cacti"

    [main.php_fpm_config]
    name = "PHP-FPM configuration"

        [main.php_fpm_config.phpversion]
        ask = "PHP version"
        type = "select"
        choices = ["7.4", "8.0", "8.1", "8.2", "8.3"]
        default = "8.3"

        [main.php_fpm_config.fpm_footprint]
        visible = "phpversion != 'none'"
        ask = "Memory footprint of the service?"
        type = "select"
        choices.low = "Low, <= 20Mb per pool"
        choices.medium = "Medium, between 20Mb and 40Mb per pool"
        choices.high = "High, > 40Mb per pool"
        choices.specific = "Use specific value"
        default = "low"

        [main.php_fpm_config.fpm_free_footprint]
        visible = "fpm_footprint == 'specific' && phpversion != 'none'"
        ask = "Memory footprint of the service?"
        type = "number"
        default = "0"
        help = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."

        [main.php_fpm_config.fpm_usage]
        visible = "phpversion != 'none'"
        ask = "Expected usage of the service?"
        type = "select"
        choices = ["low", "medium", "high"]
        default = "low"
        help = "low: Personal usage, behind the sso. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br>medium: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br>high: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."
