#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cacti"
name = "Cacti monitoring tool"
description.en = "Cacti provides a robust and extensible operational monitoring and fault management framework for users around the world. Is also a complete network graphing solution designed to harness the power of RRDTool's data storage and graphing functionality."
description.fr = "Cacti fournit un cadre de surveillance opérationnelle et de gestion des pannes robuste et extensible pour les utilisateurs du monde entier. Il s'agit également d'une solution graphique réseau complète conçue pour exploiter la puissance des fonctionnalités de stockage de données et de création de graphiques de RRDTool."

version = "1.2.28~ynh1"

maintainers = ["pihomeserver"]

[upstream]
license = "free"
website = "https://www.cacti.net/"
userdoc = "https://docs.cacti.net/README.md#cacti-overview"
code = "https://github.com/cacti/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"

architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/cacti"

    [install.init_main_permission]
    type = "group"

    [install.admin]
    type = "user"

[resources]
    [resources.system_user]
    [resources.install_dir]
    [resources.data_dir]
    [resources.permissions]
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = "cacti"

    [resources.database]
    # This will automatically provision/deprovison a MySQL DB and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    type = "mysql"
