#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cacti"
name = "Cacti monitoring tool"
description.en = "Cacti provides a robust and extensible operational monitoring and fault management framework for users around the world. Is also a complete network graphing solution designed to harness the power of RRDTool's data storage and graphing functionality."
description.fr = "Cacti fournit un cadre de surveillance opérationnelle et de gestion des pannes robuste et extensible pour les utilisateurs du monde entier. Il s'agit également d'une solution graphique réseau complète conçue pour exploiter la puissance des fonctionnalités de stockage de données et de création de graphiques de RRDTool."

version = "1.2.24~ynh1"

maintainers = ["pihomeserver"]

[upstream]
license = "free"
website = "https://www.cacti.net/"
userdoc = "https://docs.cacti.net/README.md#cacti-overview"
code = "https://github.com/cacti/"

[integration]
yunohost = ">= 12.0.0"
helpers_version = "2.1"

architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/cacti"

    [install.init_main_permission]
    type = "group"
    default = "admins"

    [install.phpversion]
    ask.en = "Choose a PHP version you want to use for your app"
    ask.fr = "Choisissez une version PHP que vous souhaitez utiliser pour votre application"
    type = "select"
    choices = ["8.0", "8.1", "8.2", "8.3"]
    default = "8.3"

    [install.admin]
    type = "user"

[resources]
    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "cacti"
