test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.custom_error_file = "0"
    args.phpversion = "8.3"
    test_upgrade_from.bf5d3ed.name = "1.0~ynh14"
    test_upgrade_from.bf5d3ed.args.with_mysql = "0"
    test_upgrade_from.bf5d3ed.args.domain = "sub.domain.tld"
    test_upgrade_from.bf5d3ed.args.path = "/"
    test_upgrade_from.bf5d3ed.args.password = "SuperDuper_StrongPassw0rd"
